"""Live parking for Nürnberg, scraped from the city's own occupancy page
(Servicebetrieb öffentlicher Raum / Tiefbauamt, "Belegung der Parkhäuser
in der Altstadt/Innenstadt"), generated by the parking-guidance system's
"SoeR1E2ParkdataPublisher" and refreshed every 15 minutes.

Nürnberg used to arrive only via the defgsus community archive under
source_id "tiefbauamt-nuernberg-parken", which scrapes this same page.
No machine-readable feed exists (nothing on Nürnberg's or Bavaria's open-
data portals, GovData has none), so this adapter reads the HTML table and
takes over that source_id.

place_ids: the archive takes the *last line* of the name cell, and the
page wraps some names over two lines in its source ("Parkhaus\\n
Hauptmarkt" -> "Hauptmarkt") but not others ("Parkhaus Karstadt"), which
is why the archive has both styles. Reproducing that rule exactly keeps
every one of the 19 garages on its existing place_id.

The page is ISO-8859-1 (fetched as bytes and decoded here, since
get_text assumes UTF-8). HTML comments are stripped first: the page keeps
an old "publication suspended" notice commented out. Capacity is the
page's "Fassungsvermögen" column (matches what is on file for all 18
garages that have one).

Timestamp: the page's "Stand vom DD.MM.YYYY, HH:MM:SS" -- local German
time (15:02:46 shown at 13:06 UTC), converted to UTC. Readings are
skipped when the free cell is empty, and always for Parkhaus City-Point,
which has reported 0 free on every reading since at least July 2026 (the
archive has nothing else for it) -- a closed garage, not a full one.
"""

from __future__ import annotations

import html
import re
from datetime import datetime, timezone
from zoneinfo import ZoneInfo

from scrapers.base import CapacityRecord, OccupancyRecord, SourceAdapter
from scrapers.util import archive_slug

BERLIN = ZoneInfo("Europe/Berlin")
PAGE_URL = "https://tiefbauamt.nuernberg.de/site/parken/parkhausbelegung/parkhaus_belegung.html"

# innermost rows only: the garage tables are nested inside layout tables
ROW_RE = re.compile(r"<tr[^>]*>((?:(?!<tr[\s>]).)*?)</tr>", re.S | re.I)
CELL_RE = re.compile(r"<td[^>]*>(.*?)</td>", re.S | re.I)
STAND_RE = re.compile(r"Stand vom\s+(\d{1,2})\.(\d{1,2})\.(\d{4}),\s*(\d{1,2}):(\d{2}):(\d{2})")

SKIP_PLACE_IDS = {"tiefbauamt-nuernberg-parken-Parkhaus-City-Point"}  # always 0 -- see module docstring


def _text(cell: str) -> str:
    return html.unescape(re.sub(r"<[^>]+>", "", cell)).replace("\xa0", " ")


def _int(cell: str) -> int | None:
    t = _text(cell).strip()
    return int(t) if t.isdigit() else None


class NuernbergLiveAdapter(SourceAdapter):
    name = "tiefbauamt-nuernberg-parken"
    fetcher_type = "http"
    occupancy_interval_seconds = 30 * 60
    capacity_interval_seconds = 7 * 24 * 3600

    def _page(self, fetcher) -> tuple[list[tuple[str, int | None, int | None]], datetime | None]:
        page = fetcher.get_bytes(PAGE_URL).decode("iso-8859-1")
        page = re.sub(r"<!--.*?-->", "", page, flags=re.S)
        rows = []
        for row in ROW_RE.findall(page):
            cells = CELL_RE.findall(row)
            # garage rows are exactly: spacer, name, free, capacity
            if len(cells) != 4:
                continue
            lines = [ln.strip() for ln in _text(cells[1]).splitlines() if ln.strip()]
            capacity = _int(cells[3])
            if not lines or capacity is None:  # header row ("Parkhausname") has no numbers
                continue
            rows.append((lines[-1], _int(cells[2]), capacity))
        m = STAND_RE.search(page)
        stand = None
        if m:
            d, mo, y, h, mi, s = map(int, m.groups())
            stand = datetime(y, mo, d, h, mi, s, tzinfo=BERLIN).astimezone(timezone.utc)
        return rows, stand

    def fetch_capacity(self, fetcher) -> list[CapacityRecord]:
        rows, _ = self._page(fetcher)
        return [
            CapacityRecord(
                place_id=f"{self.name}-{archive_slug(name)}",
                place_name=name,
                city_name="Nürnberg",
                num_all=capacity,
                source_id=self.name,
                source_web_url=PAGE_URL,
            )
            for name, _free, capacity in rows
            if capacity
        ]

    def fetch_occupancy(self, fetcher, known_garages: dict[str, str]) -> list[OccupancyRecord]:
        rows, stand = self._page(fetcher)
        ts = (stand or datetime.now(timezone.utc)).isoformat(timespec="seconds")
        records = []
        for name, free, _capacity in rows:
            place_id = f"{self.name}-{archive_slug(name)}"
            if free is None or place_id in SKIP_PLACE_IDS:
                continue
            records.append(OccupancyRecord(place_id=place_id, ts=ts, free=free))
        return records
